In [1]:
import pandas as pd

In [2]:
df1 = pd.read_csv('error_message.csv')

In [3]:
df1.head(3)

,메세지,발생시간,조치시간,정지시간,정지시간2,모델,제품두께,제품싸이즈,작업구분,작업자,온도,습도
0,e-CIM 관련에러,2015-06-17T07:32:42,2015-06-17T07:32:54,0시 00분 12초,11.970,78FBGA 7.5x11 CGHB08154 REV.1,0.25,415-515,야간,이은미,22.5,47.3
1,Door Open,2015-06-17T07:32:42,2015-06-17T07:32:54,0시 00분 12초,11.970,78FBGA 7.5x11 CGHB08154 REV.1,0.25,415-515,야간,이은미,22.5,47.3
2,롯트 종료,2015-06-17T07:33:00,2015-06-17T07:33:05,0시 00분 04초,4.093,78FBGA 7.5x11 CGHB08154 REV.2,1.25,415-516,야간,이은미,22.5,47.3

In [4]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2792 entries, 0 to 2791
Data columns (total 12 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   메세지     2792 non-null   object
 1   발생시간    2792 non-null   object
 2   조치시간    2792 non-null   object
 3   정지시간    2792 non-null   object
 4   정지시간2   2792 non-null   float64
 5   모델      1112 non-null   object
 6   제품두께    1112 non-null   object
 7   제품싸이즈   1112 non-null   object
 8   작업구분    2792 non-null   object
 9   작업자     1112 non-null   object
 10  온도      2792 non-null   float64
 11  습도      2792 non-null   float64
dtypes: float64(3), object(9)
memory usage: 261.9+ KB

In [5]:
df1.describe()

              정지시간2      온도            습도
count   2792.000000  2792.0  2.792000e+03
mean      73.133777    22.5  4.730000e+01
std      490.559231     0.0  7.106700e-15
min        1.391000    22.5  4.730000e+01
25%        6.015000    22.5  4.730000e+01
50%       11.956000    22.5  4.730000e+01
75%       29.254250    22.5  4.730000e+01
max    12863.000000    22.5  4.730000e+01

In [6]:
df1['메세지']

0       e-CIM 관련에러
1        Door Open
2            롯트 종료
3        Door Open
4        Door Open
           ...
2787      메가진 Full
2788     Door Open
2789      메가진 Full
2790         롯트 종료
2791     Door Open
Name: 메세지, Length: 2792, dtype: object

In [7]:
df1['메세지'].unique()

array(['e-CIM 관련에러', 'Door Open', '롯트 종료', '자재 픽업 에러', '비젼 가동 준비 Error',
       '타임 오버', 'SYSTEM HANG UP', '초기화 Error', '메가진 Full', 'ITS 데이터',
       '드라이버 알람', '비젼 데이터', '컨드롤러 알람'], dtype=object)

In [8]:
df1['메세지'].value_counts()

메세지
Door Open         1345
자재 픽업 에러           425
비젼 가동 준비 Error     234
롯트 종료              229
초기화 Error          215
e-CIM 관련에러         133
메가진 Full           119
타임 오버               45
SYSTEM HANG UP      35
비젼 데이터               6
ITS 데이터              3
드라이버 알람              2
컨드롤러 알람              1
Name: count, dtype: int64

In [9]:
df1.describe(include=object)

,메세지,발생시간,조치시간,정지시간,모델,제품두께,제품싸이즈,작업구분,작업자
count,2792,2792,2792,2792,1112,1112,1112,2792,1112
unique,13,2791,2791,283,62,45,21,2,7
top,Door Open,2015-06-17T07:32:42,2015-06-17T07:32:54,0시 00분 06초,GU1413F,0.21,415-515,주간,최이슬
freq,1345,2,2,307,102,214,812,1466,453

In [10]:
df1.sort_values(by='정지시간2')
# 데이터 정렬 (오름차순)

,메세지,발생시간,조치시간,정지시간,정지시간2,모델,제품두께,제품싸이즈,작업구분,작업자,온도,습도
67,Door Open,2015-06-17T09:35:26,2015-06-17T09:35:28,0시 00분 01초,1.391,(BGA) 54-50-03786-DT-R1F-37,6.13,415-520,주간,임내순,22.5,47.3
565,Door Open,2015-06-18T10:13:16,2015-06-18T10:13:18,0시 00분 02초,1.859,NaN,NaN,NaN,주간,NaN,22.5,47.3
1056,자재 픽업 에러,2015-06-19T14:16:51,2015-06-19T14:16:52,0시 00분 02초,1.859,NaN,NaN,NaN,주간,NaN,22.5,47.3
13,Door Open,2015-06-17T07:45:47,2015-06-17T07:45:48,0시 00분 02초,1.874,78FBGA 7.5x11 CGHB08154 REV.13,12.25,415-527,야간,이은미,22.5,47.3
151,초기화 Error,2015-06-17T15:02:23,2015-06-17T15:02:25,0시 00분 02초,1.891,NaN,NaN,NaN,주간,NaN,22.5,47.3
...,...,...,...,...,...,...,...,...,...,...,...,...
807,Door Open,2015-06-18T22:00:44,2015-06-18T23:39:23,1시 38분 39초,5918.700,038072E A(R001-9116U)(ITS-A)(update strip),0.38,415-515,야간,장다혜,22.5,47.3
2100,Door Open,2015-06-22T11:41:40,2015-06-22T13:47:15,2시 05분 35초,7535.100,NaN,NaN,NaN,주간,NaN,22.5,47.3
2167,Door Open,2015-06-22T17:40:15,2015-06-22T20:04:06,2시 23분 51초,8630.500,NaN,NaN,NaN,주간,NaN,22.5,47.3
1771,초기화 Error,2015-06-21T12:32:16,2015-06-21T16:05:44,3시 33분 28초,12808.000,FCCSP597MLA REV.1(ETP)(ITS-A),0.15,417-518,주간,박상훈,22.5,47.3
1533,초기화 Error,2015-06-20T17:58:25,2015-06-20T21:32:48,3시 34분 23초,12863.000,NaN,NaN,NaN,야간,NaN,22.5,47.3

In [12]:
df1.sort_values(by = '정지시간2', ascending=False)
# 데이터 정렬 (내림차순)

,메세지,발생시간,조치시간,정지시간,정지시간2,모델,제품두께,제품싸이즈,작업구분,작업자,온도,습도
1533,초기화 Error,2015-06-20T17:58:25,2015-06-20T21:32:48,3시 34분 23초,12863.000,NaN,NaN,NaN,야간,NaN,22.5,47.3
1771,초기화 Error,2015-06-21T12:32:16,2015-06-21T16:05:44,3시 33분 28초,12808.000,FCCSP597MLA REV.1(ETP)(ITS-A),0.15,417-518,주간,박상훈,22.5,47.3
2167,Door Open,2015-06-22T17:40:15,2015-06-22T20:04:06,2시 23분 51초,8630.500,NaN,NaN,NaN,주간,NaN,22.5,47.3
2100,Door Open,2015-06-22T11:41:40,2015-06-22T13:47:15,2시 05분 35초,7535.100,NaN,NaN,NaN,주간,NaN,22.5,47.3
807,Door Open,2015-06-18T22:00:44,2015-06-18T23:39:23,1시 38분 39초,5918.700,038072E A(R001-9116U)(ITS-A)(update strip),0.38,415-515,야간,장다혜,22.5,47.3
...,...,...,...,...,...,...,...,...,...,...,...,...
2445,e-CIM 관련에러,2015-06-23T16:07:55,2015-06-23T16:07:57,0시 00분 02초,1.891,NaN,NaN,NaN,주간,NaN,22.5,47.3
13,Door Open,2015-06-17T07:45:47,2015-06-17T07:45:48,0시 00분 02초,1.874,78FBGA 7.5x11 CGHB08154 REV.13,12.25,415-527,야간,이은미,22.5,47.3
1056,자재 픽업 에러,2015-06-19T14:16:51,2015-06-19T14:16:52,0시 00분 02초,1.859,NaN,NaN,NaN,주간,NaN,22.5,47.3
565,Door Open,2015-06-18T10:13:16,2015-06-18T10:13:18,0시 00분 02초,1.859,NaN,NaN,NaN,주간,NaN,22.5,47.3
67,Door Open,2015-06-17T09:35:26,2015-06-17T09:35:28,0시 00분 01초,1.391,(BGA) 54-50-03786-DT-R1F-37,6.13,415-520,주간,임내순,22.5,47.3

In [13]:
df1.iloc[0:100]
# 데이터 추출 (행단위, iloc : index location)
    # 0번째부터 99번째까지 100개 데이터를 추출
    # head()와 유사함

,메세지,발생시간,조치시간,정지시간,정지시간2,모델,제품두께,제품싸이즈,작업구분,작업자,온도,습도
0,e-CIM 관련에러,2015-06-17T07:32:42,2015-06-17T07:32:54,0시 00분 12초,11.970,78FBGA 7.5x11 CGHB08154 REV.1,0.25,415-515,야간,이은미,22.5,47.3
1,Door Open,2015-06-17T07:32:42,2015-06-17T07:32:54,0시 00분 12초,11.970,78FBGA 7.5x11 CGHB08154 REV.1,0.25,415-515,야간,이은미,22.5,47.3
2,롯트 종료,2015-06-17T07:33:00,2015-06-17T07:33:05,0시 00분 04초,4.093,78FBGA 7.5x11 CGHB08154 REV.2,1.25,415-516,야간,이은미,22.5,47.3
3,Door Open,2015-06-17T07:36:25,2015-06-17T07:36:29,0시 00분 04초,4.093,78FBGA 7.5x11 CGHB08154 REV.3,2.25,415-517,야간,이은미,22.5,47.3
4,Door Open,2015-06-17T07:37:54,2015-06-17T07:41:58,0시 04분 04초,244.350,78FBGA 7.5x11 CGHB08154 REV.4,3.25,415-518,야간,이은미,22.5,47.3
...,...,...,...,...,...,...,...,...,...,...,...,...
95,e-CIM 관련에러,2015-06-17T11:30:44,2015-06-17T11:30:46,0시 00분 02초,2.016,NaN,NaN,NaN,주간,NaN,22.5,47.3
96,e-CIM 관련에러,2015-06-17T11:49:08,2015-06-17T11:49:26,0시 00분 18초,18.031,NaN,NaN,NaN,주간,NaN,22.5,47.3
97,e-CIM 관련에러,2015-06-17T11:53:36,2015-06-17T11:54:05,0시 00분 29초,29.254,NaN,NaN,NaN,주간,NaN,22.5,47.3
98,Door Open,2015-06-17T11:59:56,2015-06-17T12:00:06,0시 00분 10초,10.345,NaN,NaN,NaN,주간,NaN,22.5,47.3
99,Door Open,2015-06-17T12:00:06,2015-06-17T12:04:02,0시 03분 55초,235.280,NaN,NaN,NaN,주간,NaN,22.5,47.3

In [14]:
df1[['메세지','정지시간2','작업구분','작업자']]
# 데이터 추출 (열단위)
# Dataframe 형태로 데이터 추출
    # Series : index - value / []
    # Dataframe : index - column - value / [[]]

             메세지    정지시간2 작업구분  작업자
0     e-CIM 관련에러   11.970   야간  이은미
1      Door Open   11.970   야간  이은미
2          롯트 종료    4.093   야간  이은미
3      Door Open    4.093   야간  이은미
4      Door Open  244.350   야간  이은미
...          ...      ...  ...  ...
2787    메가진 Full  252.560   주간  NaN
2788   Door Open   25.956   주간  NaN
2789    메가진 Full    8.063   주간  NaN
2790       롯트 종료    4.281   주간  NaN
2791   Door Open    4.078   주간  NaN

[2792 rows x 4 columns]

In [16]:
cond1 = (df1['정지시간2'] >= 600)
df1.loc[cond1]

,메세지,발생시간,조치시간,정지시간,정지시간2,모델,제품두께,제품싸이즈,작업구분,작업자,온도,습도
454,Door Open,2015-06-18T05:00:04,2015-06-18T05:29:32,0시 29분 28초,1768.40,(MicroSD) 54-50-04236-DA-R4N-33,415-515,0.21,야간,정승희,22.5,47.3
524,Door Open,2015-06-18T09:02:35,2015-06-18T09:24:11,0시 21분 36초,1295.90,NaN,NaN,NaN,주간,NaN,22.5,47.3
731,롯트 종료,2015-06-18T17:53:04,2015-06-18T18:03:41,0시 10분 37초,637.09,NaN,NaN,NaN,주간,NaN,22.5,47.3
807,Door Open,2015-06-18T22:00:44,2015-06-18T23:39:23,1시 38분 39초,5918.70,038072E A(R001-9116U)(ITS-A)(update strip),0.38,415-515,야간,장다혜,22.5,47.3
855,Door Open,2015-06-19T01:30:12,2015-06-19T01:54:26,0시 24분 14초,1453.90,038072E A(R001-9116U)(ITS-A)(update strip),0.38,415-515,야간,장다혜,22.5,47.3
873,초기화 Error,2015-06-19T02:51:34,2015-06-19T03:44:02,0시 52분 28초,3148.40,01009004-1-48,0.21,415-515,야간,장다혜,22.5,47.3
993,e-CIM 관련에러,2015-06-19T10:12:03,2015-06-19T10:27:40,0시 15분 36초,936.39,NaN,NaN,NaN,주간,NaN,22.5,47.3
1128,메가진 Full,2015-06-19T18:31:19,2015-06-19T19:16:44,0시 45분 24초,2724.10,NaN,NaN,NaN,주간,NaN,22.5,47.3
1135,Door Open,2015-06-19T19:25:13,2015-06-19T19:36:42,0시 11분 29초,689.17,NaN,NaN,NaN,주간,NaN,22.5,47.3
1137,Door Open,2015-06-19T19:57:45,2015-06-19T20:15:04,0시 17분 19초,1039.00,NaN,NaN,NaN,주간,NaN,22.5,47.3
1138,Door Open,2015-06-19T20:15:04,2015-06-19T20:40:02,0시 24분 58초,1498.20,NaN,NaN,NaN,주간,NaN,22.5,47.3
1161,초기화 Error,2015-06-19T21:01:39,2015-06-19T21:19:31,0시 17분 52초,1072.50,NaN,NaN,NaN,주간,NaN,22.5,47.3
1390,Door Open,2015-06-20T07:44:50,2015-06-20T08:38:06,0시 53분 16초,3196.40,54-50-19938-1(R001-A092X)(01)(NS),0.21,415-515,주간,최이슬,22.5,47.3
1442,자재 픽업 에러,2015-06-20T11:07:17,2015-06-20T12:39:04,1시 31분 47초,5507.20,NaN,NaN,NaN,주간,NaN,22.5,47.3
1519,Door Open,2015-06-20T16:53:18,2015-06-20T17:10:03,0시 16분 45초,1004.90,NaN,NaN,NaN,주간,NaN,22.5,47.3
1533,초기화 Error,2015-06-20T17:58:25,2015-06-20T21:32:48,3시 34분 23초,12863.00,NaN,NaN,NaN,야간,NaN,22.5,47.3
1558,Door Open,2015-06-20T23:16:02,2015-06-20T23:37:46,0시 21분 44초,1303.80,PB7GB9J1(1) _ MCP,0.12,415-515,야간,최이슬,22.5,47.3
1687,Door Open,2015-06-21T07:55:02,2015-06-21T08:36:35,0시 41분 34초,2493.50,NaN,NaN,NaN,주간,NaN,22.5,47.3
1697,비젼 가동 준비 Error,2015-06-21T09:27:53,2015-06-21T09:51:16,0시 23분 24초,1403.60,NaN,NaN,NaN,주간,NaN,22.5,47.3
1771,초기화 Error,2015-06-21T12:32:16,2015-06-21T16:05:44,3시 33분 28초,12808.00,FCCSP597MLA REV.1(ETP)(ITS-A),0.15,417-518,주간,박상훈,22.5,47.3
1818,Door Open,2015-06-21T17:54:20,2015-06-21T18:05:27,0시 11분 07초,666.97,SD(PB7F97V1(1)),0.255,415-515,주간,박상훈,22.5,47.3
1844,초기화 Error,2015-06-21T19:34:23,2015-06-21T21:10:33,1시 36분 10초,5770.30,NaN,NaN,NaN,야간,NaN,22.5,47.3
1898,Door Open,2015-06-22T00:38:47,2015-06-22T00:53:36,0시 14분 49초,889.06,NaN,NaN,NaN,야간,NaN,22.5,47.3
1947,초기화 Error,2015-06-22T04:55:48,2015-06-22T05:06:01,0시 10분 13초,613.25,GU1413F,0.56,415-515,야간,최이슬,22.5,47.3
1967,초기화 Error,2015-06-22T07:11:38,2015-06-22T07:23:22,0시 11분 45초,704.55,NaN,NaN,NaN,야간,NaN,22.5,47.3
2005,Door Open,2015-06-22T08:17:43,2015-06-22T08:58:34,0시 40분 51초,2451.40,NaN,NaN,NaN,주간,NaN,22.5,47.3
2062,비젼 가동 준비 Error,2015-06-22T09:31:38,2015-06-22T09:44:00,0시 12분 23초,742.55,NaN,NaN,NaN,주간,NaN,22.5,47.3
2071,초기화 Error,2015-06-22T09:51:50,2015-06-22T10:04:52,0시 13분 02초,781.67,NaN,NaN,NaN,주간,NaN,22.5,47.3
2088,Door Open,2015-06-22T10:19:26,2015-06-22T11:32:36,1시 13분 10초,4390.20,NaN,NaN,NaN,주간,NaN,22.5,47.3
2100,Door Open,2015-06-22T11:41:40,2015-06-22T13:47:15,2시 05분 35초,7535.10,NaN,NaN,NaN,주간,NaN,22.5,47.3
2125,자재 픽업 에러,2015-06-22T14:51:23,2015-06-22T15:52:32,1시 01분 09초,3668.90,NaN,NaN,NaN,주간,NaN,22.5,47.3
2150,초기화 Error,2015-06-22T16:18:00,2015-06-22T16:59:01,0시 41분 01초,2461.30,NaN,NaN,NaN,주간,NaN,22.5,47.3
2167,Door Open,2015-06-22T17:40:15,2015-06-22T20:04:06,2시 23분 51초,8630.50,NaN,NaN,NaN,주간,NaN,22.5,47.3
2221,비젼 가동 준비 Error,2015-06-22T22:54:24,2015-06-22T23:07:14,0시 12분 50초,770.43,101388443(ETP)(B),0.15,417-518,야간,최이슬,22.5,47.3
2265,Door Open,2015-06-23T02:50:08,2015-06-23T03:17:24,0시 27분 16초,1635.80,NaN,NaN,NaN,야간,NaN,22.5,47.3
2270,초기화 Error,2015-06-23T04:14:57,2015-06-23T04:32:49,0시 17분 52초,1072.10,NaN,NaN,NaN,야간,NaN,22.5,47.3
2639,e-CIM 관련에러,2015-06-24T03:26:42,2015-06-24T04:10:49,0시 44분 07초,2647.10,NaN,NaN,NaN,야간,NaN,22.5,47.3
2642,Door Open,2015-06-24T04:11:23,2015-06-24T04:21:30,0시 10분 07초,607.28,NaN,NaN,NaN,야간,NaN,22.5,47.3
2708,비젼 가동 준비 Error,2015-06-24T09:07:07,2015-06-24T09:17:59,0시 10분 52초,652.00,NaN,NaN,NaN,주간,NaN,22.5,47.3

In [22]:
cond1 = (df1['정지시간2'] >= 600)
cond2 = (df1['작업구분'] == '야간')

df1.loc[cond1 & cond2]
# 두 조건을 모두 만족하는 데이터만 추출

,메세지,발생시간,조치시간,정지시간,정지시간2,모델,제품두께,제품싸이즈,작업구분,작업자,온도,습도
454,Door Open,2015-06-18T05:00:04,2015-06-18T05:29:32,0시 29분 28초,1768.40,(MicroSD) 54-50-04236-DA-R4N-33,415-515,0.21,야간,정승희,22.5,47.3
807,Door Open,2015-06-18T22:00:44,2015-06-18T23:39:23,1시 38분 39초,5918.70,038072E A(R001-9116U)(ITS-A)(update strip),0.38,415-515,야간,장다혜,22.5,47.3
855,Door Open,2015-06-19T01:30:12,2015-06-19T01:54:26,0시 24분 14초,1453.90,038072E A(R001-9116U)(ITS-A)(update strip),0.38,415-515,야간,장다혜,22.5,47.3
873,초기화 Error,2015-06-19T02:51:34,2015-06-19T03:44:02,0시 52분 28초,3148.40,01009004-1-48,0.21,415-515,야간,장다혜,22.5,47.3
1533,초기화 Error,2015-06-20T17:58:25,2015-06-20T21:32:48,3시 34분 23초,12863.00,NaN,NaN,NaN,야간,NaN,22.5,47.3
1558,Door Open,2015-06-20T23:16:02,2015-06-20T23:37:46,0시 21분 44초,1303.80,PB7GB9J1(1) _ MCP,0.12,415-515,야간,최이슬,22.5,47.3
1844,초기화 Error,2015-06-21T19:34:23,2015-06-21T21:10:33,1시 36분 10초,5770.30,NaN,NaN,NaN,야간,NaN,22.5,47.3
1898,Door Open,2015-06-22T00:38:47,2015-06-22T00:53:36,0시 14분 49초,889.06,NaN,NaN,NaN,야간,NaN,22.5,47.3
1947,초기화 Error,2015-06-22T04:55:48,2015-06-22T05:06:01,0시 10분 13초,613.25,GU1413F,0.56,415-515,야간,최이슬,22.5,47.3
1967,초기화 Error,2015-06-22T07:11:38,2015-06-22T07:23:22,0시 11분 45초,704.55,NaN,NaN,NaN,야간,NaN,22.5,47.3
2221,비젼 가동 준비 Error,2015-06-22T22:54:24,2015-06-22T23:07:14,0시 12분 50초,770.43,101388443(ETP)(B),0.15,417-518,야간,최이슬,22.5,47.3
2265,Door Open,2015-06-23T02:50:08,2015-06-23T03:17:24,0시 27분 16초,1635.80,NaN,NaN,NaN,야간,NaN,22.5,47.3
2270,초기화 Error,2015-06-23T04:14:57,2015-06-23T04:32:49,0시 17분 52초,1072.10,NaN,NaN,NaN,야간,NaN,22.5,47.3
2639,e-CIM 관련에러,2015-06-24T03:26:42,2015-06-24T04:10:49,0시 44분 07초,2647.10,NaN,NaN,NaN,야간,NaN,22.5,47.3
2642,Door Open,2015-06-24T04:11:23,2015-06-24T04:21:30,0시 10분 07초,607.28,NaN,NaN,NaN,야간,NaN,22.5,47.3

In [23]:
cond1 = (df1['정지시간2'] >= 600)
cond2 = (df1['메세지'] == '초기화 Error')

df1.loc[cond1 | cond2]
# 두 조건 중 하나라도 만족하면 데이터를 추출

,메세지,발생시간,조치시간,정지시간,정지시간2,모델,제품두께,제품싸이즈,작업구분,작업자,온도,습도
79,초기화 Error,2015-06-17T10:24:25,2015-06-17T10:24:37,0시 00분 12초,11.924,NaN,NaN,NaN,주간,NaN,22.5,47.3
104,초기화 Error,2015-06-17T12:20:53,2015-06-17T12:20:59,0시 00분 06초,5.985,NaN,NaN,NaN,주간,NaN,22.5,47.3
106,초기화 Error,2015-06-17T12:21:09,2015-06-17T12:21:29,0시 00분 20초,20.094,NaN,NaN,NaN,주간,NaN,22.5,47.3
108,초기화 Error,2015-06-17T12:54:24,2015-06-17T12:54:40,0시 00분 16초,15.891,NaN,NaN,NaN,주간,NaN,22.5,47.3
150,초기화 Error,2015-06-17T15:01:43,2015-06-17T15:01:51,0시 00분 08초,7.970,NaN,NaN,NaN,주간,NaN,22.5,47.3
...,...,...,...,...,...,...,...,...,...,...,...,...
2720,초기화 Error,2015-06-24T10:00:32,2015-06-24T10:03:51,0시 03분 18초,198.420,NaN,NaN,NaN,주간,NaN,22.5,47.3
2721,초기화 Error,2015-06-24T10:03:51,2015-06-24T10:03:53,0시 00분 02초,2.016,NaN,NaN,NaN,주간,NaN,22.5,47.3
2756,초기화 Error,2015-06-24T11:08:15,2015-06-24T11:08:21,0시 00분 06초,6.001,NaN,NaN,NaN,주간,NaN,22.5,47.3
2757,초기화 Error,2015-06-24T11:08:21,2015-06-24T11:08:33,0시 00분 13초,12.516,NaN,NaN,NaN,주간,NaN,22.5,47.3
2776,초기화 Error,2015-06-24T11:18:27,2015-06-24T11:18:29,0시 00분 02초,2.032,NaN,NaN,NaN,주간,NaN,22.5,47.3

In [25]:
df1.pivot_table(index='메세지',values='정지시간2',aggfunc= 'mean')
# 데이터 요약

                     정지시간2
메세지
Door Open        67.562041
ITS 데이터          52.978333
SYSTEM HANG UP   20.721886
e-CIM 관련에러       73.292000
드라이버 알람          50.887000
롯트 종료            43.841712
메가진 Full         44.304277
비젼 가동 준비 Error   58.614436
비젼 데이터           65.188167
자재 픽업 에러         49.007108
초기화 Error       233.085367
컨드롤러 알람           4.032000
타임 오버            49.343889

In [44]:
# 메세지 항목에서 'Door Open'에 해당하는 오류들 중에 '정지시간2'이 가장 오래 걸린 상위 100개 데이터를 추출
cond1 = (df1['메세지'] == 'Door Open')
df1.loc[cond1].sort_values(by = '정지시간2', ascending= False).head(100)

,메세지,발생시간,조치시간,정지시간,정지시간2,모델,제품두께,제품싸이즈,작업구분,작업자,온도,습도
2167,Door Open,2015-06-22T17:40:15,2015-06-22T20:04:06,2시 23분 51초,8630.50,NaN,NaN,NaN,주간,NaN,22.5,47.3
2100,Door Open,2015-06-22T11:41:40,2015-06-22T13:47:15,2시 05분 35초,7535.10,NaN,NaN,NaN,주간,NaN,22.5,47.3
807,Door Open,2015-06-18T22:00:44,2015-06-18T23:39:23,1시 38분 39초,5918.70,038072E A(R001-9116U)(ITS-A)(update strip),0.38,415-515,야간,장다혜,22.5,47.3
2088,Door Open,2015-06-22T10:19:26,2015-06-22T11:32:36,1시 13분 10초,4390.20,NaN,NaN,NaN,주간,NaN,22.5,47.3
1390,Door Open,2015-06-20T07:44:50,2015-06-20T08:38:06,0시 53분 16초,3196.40,54-50-19938-1(R001-A092X)(01)(NS),0.21,415-515,주간,최이슬,22.5,47.3
...,...,...,...,...,...,...,...,...,...,...,...,...
2707,Door Open,2015-06-24T09:04:58,2015-06-24T09:07:07,0시 02분 09초,129.50,NaN,NaN,NaN,주간,NaN,22.5,47.3
2193,Door Open,2015-06-22T21:37:00,2015-06-22T21:39:09,0시 02분 09초,128.99,NaN,NaN,NaN,야간,NaN,22.5,47.3
1913,Door Open,2015-06-22T02:16:55,2015-06-22T02:19:03,0시 02분 08초,128.08,NaN,NaN,NaN,야간,NaN,22.5,47.3
679,Door Open,2015-06-18T14:37:09,2015-06-18T14:39:16,0시 02분 07초,127.37,1B36917(Denali-2)(ETP)(NEW)(0.1%),0.15,417-518,주간,임내순,22.5,47.3
648,Door Open,2015-06-18T13:50:35,2015-06-18T13:52:42,0시 02분 07초,126.93,1B36917(Denali-2)(ETP)(NEW)(0.1%),0.15,417-518,주간,임내순,22.5,47.3

In [53]:
# '정지시간2'가 300초 이상이면서, '작업자'가 '이은미'인 데이터를 추출해 '정지시간2'의 요약통계량을 확인
cond1 = (df1['정지시간2'] >= 300)
cond2 = (df1['작업자'] == '이은미')
df1.loc[cond1 & cond2].describe()

,메세지,발생시간,조치시간,정지시간,모델,제품두께,제품싸이즈,작업구분,작업자
count,2,2,2,2,2,2,2,2,2
unique,2,2,2,2,2,2,1,1,1
top,Door Open,2015-06-23T12:41:33,2015-06-23T12:47:48,0시 06분 15초,microSD(CAA862-00)E/B,0.21,415-515,주간,이은미
freq,1,1,1,1,1,1,2,2,2